repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code
        entry: cargo fmt --manifest-path backend/Cargo.toml --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check Rust code
        entry: cargo check --manifest-path backend/Cargo.toml --workspace
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code
        entry: cargo clippy --manifest-path backend/Cargo.toml --workspace -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
