version: '3.8'

services:
  rustfs-test:
    image: rustfs/rustfs:latest
    container_name: rustfs-test
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - rustfs_test_data:/data

  temporal-test:
    image: temporalio/temporal:latest
    container_name: temporal-test
    ports:
      - "7234:7233"
      - "8234:8233"
    command: server start-dev --ip 0.0.0.0 --db-filename /tmp/temporal-test.db

volumes:
  rustfs_test_data:
